# GitHub Action Workflow to Deploy Nodejs to AWS ElasticBeanstalk
# Made by Rajeev Singh Jadon
name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  EB_PACKAGE_S3_BUCKET_NAME: "devops-cicd-assignment-0409"
  EB_APPLICATION_NAME: "Node-js"
  EB_ENVIRONMENT_NAME: "Node-js-env"
  DEPLOY_PACKAGE_NAME: "nodejs-app-${{ github.sha }}.zip"
  AWS_REGION_NAME: "ap-northeast-1"
on:
  push:
    branches:
      - master
jobs:
  my_ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repository
        uses: actions/checkout@v1

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure my AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Copy our Deployment package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{
          env.EB_PACKAGE_S3_BUCKET_NAME}}/

      - name: Notify Slack
        uses: act10ns/slack@v1.2.2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#ci-cd"
          message: Integration {{ env.GITHUB_REF_NAME }} branch Successfully
        if: always()

  my_cd_pipeline:
    runs-on: ubuntu-latest
    needs: [my_ci_pipeline]

    steps:
      - name: Configure my AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Create new ElasticBeanstalk Applicaiton Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ 
            env.DEPLOY_PACKAGE_NAME }}" \
            --version-label "Ver-${{ github.sha }}" \
            --description "CommitSHA-${{ github.sha }}"
      - name: Deploy our new Application Version
        run : aws elasticbeanstalk update-environment --environment-name ${{
          env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"

      - name: Notify Slack
        uses: act10ns/slack@v1.2.2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#ci-cd"
          message: Deployed {{ env.GITHUB_REF_NAME }} branch Successfully
        if: always()
